-- MySQL Script generated by MySQL Workbench
-- Tue Jan 30 04:15:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema r3db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema r3db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `r3db` DEFAULT CHARACTER SET utf8 ;
USE `r3db` ;

-- -----------------------------------------------------
-- Table `r3db`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r3db`.`service` ;

CREATE TABLE IF NOT EXISTS `r3db`.`service` (
  `idservice` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(150) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`idservice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r3db`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r3db`.`client` ;

CREATE TABLE IF NOT EXISTS `r3db`.`client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `idservice` INT NULL DEFAULT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(45) NULL DEFAULT NULL,
  `isactive` TINYINT NOT NULL DEFAULT 1,
  `createdate` DATETIME NOT NULL,
  `inactivedate` DATETIME NULL DEFAULT NULL,
  `css` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idclient`),
  INDEX `fk_client_service1_idx` (`idservice` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_client_service1`
    FOREIGN KEY (`idservice`)
    REFERENCES `r3db`.`service` (`idservice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r3db`.`service_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r3db`.`service_record` ;

CREATE TABLE IF NOT EXISTS `r3db`.`service_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idservice` INT NOT NULL,
  `idclient` INT NOT NULL,
  `initdate` DATETIME NOT NULL,
  `enddate` DATETIME NOT NULL,
  `status` INT NOT NULL,
  `isactive` TINYINT NOT NULL DEFAULT 1,
  INDEX `fk_serv-record_servicio1_idx` (`idservice` ASC),
  INDEX `fk_serv-record_client1_idx` (`idclient` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_serv-record_servicio1`
    FOREIGN KEY (`idservice`)
    REFERENCES `r3db`.`service` (`idservice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serv-record_client1`
    FOREIGN KEY (`idclient`)
    REFERENCES `r3db`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r3db`.`card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r3db`.`card` ;

CREATE TABLE IF NOT EXISTS `r3db`.`card` (
  `serial` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `idclient` INT NOT NULL,
  `cardtype` INT NOT NULL,
  `isactive` TINYINT NOT NULL DEFAULT 1,
  `createdate` DATETIME NOT NULL,
  `inactivedate` DATETIME NULL DEFAULT NULL,
  `latitude` FLOAT NULL DEFAULT NULL,
  `longitude` FLOAT NULL DEFAULT NULL,
  `desc` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`serial`),
  INDEX `fk_card_client1_idx` (`idclient` ASC),
  CONSTRAINT `fk_card_client1`
    FOREIGN KEY (`idclient`)
    REFERENCES `r3db`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r3db`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r3db`.`report` ;

CREATE TABLE IF NOT EXISTS `r3db`.`report` (
  `idreport` INT NOT NULL AUTO_INCREMENT,
  `idclient` INT NOT NULL,
  `rules` VARCHAR(300) NOT NULL,
  `createdate` DATETIME NOT NULL,
  PRIMARY KEY (`idreport`),
  INDEX `fk_report_client1_idx` (`idclient` ASC),
  CONSTRAINT `fk_report_client1`
    FOREIGN KEY (`idclient`)
    REFERENCES `r3db`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r3db`.`cat_service_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r3db`.`cat_service_type` ;

CREATE TABLE IF NOT EXISTS `r3db`.`cat_service_type` (
  `key` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(100) NULL DEFAULT NULL,
  `isactive` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r3db`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r3db`.`role` ;

CREATE TABLE IF NOT EXISTS `r3db`.`role` (
  `idrole` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r3db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r3db`.`user` ;

CREATE TABLE IF NOT EXISTS `r3db`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `idclient` INT NULL DEFAULT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `lastlogin` DATETIME NULL DEFAULT NULL,
  `isactive` TINYINT NOT NULL DEFAULT 0,
  `createdate` DATETIME NOT NULL,
  `inactivedate` DATETIME NULL DEFAULT NULL,
  `loginfails` SMALLINT(6) NOT NULL,
  `secret` VARCHAR(45) NOT NULL,
  `secretanswer` VARCHAR(45) NOT NULL,
  `recoverytoken` VARCHAR(45) NULL DEFAULT NULL,
  `reload` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_client1_idx` (`idclient` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_user_client1`
    FOREIGN KEY (`idclient`)
    REFERENCES `r3db`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r3db`.`cat_card_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r3db`.`cat_card_type` ;

CREATE TABLE IF NOT EXISTS `r3db`.`cat_card_type` (
  `key` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(100) NULL DEFAULT NULL,
  `isactive` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r3db`.`cat_service_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r3db`.`cat_service_status` ;

CREATE TABLE IF NOT EXISTS `r3db`.`cat_service_status` (
  `key` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(100) NULL DEFAULT NULL,
  `isactive` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r3db`.`cat_cardmsg_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r3db`.`cat_cardmsg_type` ;

CREATE TABLE IF NOT EXISTS `r3db`.`cat_cardmsg_type` (
  `key` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(100) NULL DEFAULT NULL,
  `isactive` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r3db`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r3db`.`user_role` ;

CREATE TABLE IF NOT EXISTS `r3db`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  `role_idrole` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_table1_user1_idx` (`user_iduser` ASC),
  INDEX `fk_table1_role1_idx` (`role_idrole` ASC),
  CONSTRAINT `fk_table1_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `r3db`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `r3db`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `r3db`.`cat_report_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r3db`.`cat_report_type` ;

CREATE TABLE IF NOT EXISTS `r3db`.`cat_report_type` (
  `key` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(100) NULL DEFAULT NULL,
  `isactive` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`key`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
